import {
    CURVE_FRAX_3CRV_GAUGE,
    CURVE_TRI_USDC_WBTC_ETH_GAUGE,
    CURVE_crvUSD_USDT_GAUGE,
    CURVE_STG_USDC_GAUGE,
    CURVE_SDCRV_CRV_GAUGE,
    CURVE_crvUSD_USDC_GAUGE,
    CURVE_FRXETH_ETH_GAUGE,
    CURVE_TRI_USDT_WBTC_ETH_1_GAUGE,
    CURVE_TRI_crvUSD_TBTC_WSTETH_GAUGE,
    CURVE_AGEUR_EUROC_GAUGE,
    CURVE_MIM_DAI_USDC_USDT_GAUGE,
    CURVE_CVXCRV_CRV_GAUGE,
    CURVE_SDFXS_FXS_GAUGE,
    CURVE_FRAX_USDC_GAUGE,
    CURVE_ALUSD_FRAX_USDC_GAUGE,
    CURVE_TRI_USDT_WBTC_ETH_2_GAUGE,
    CURVE_RETH_ETH_GAUGE,
    CURVE_crvUSD_XAI_GAUGE,
    CURVE_COIL_FRAX_USDC_GAUGE,
    CURVE_crvUSD_SUSD_GAUGE,
    CURVE_crvUSD_DOLA_GAUGE,
    CURVE_TRI_crvUSD_ETH_CRV_GAUGE,
    CURVE_MKUSD_FRAX_USDC_GAUGE,
    CURVE_CNC_ETH_GAUGE,
    CURVE_XAI_FRAX_USDC_GAUGE,
    CURVE_TRI_crvUSD_FRXETH_SDT_GAUGE,
    CURVE_STETH_ETH_GAUGE,
    CURVE_DETH_FRXETH_GAUGE,
    CURVE_crvUSD_FRAX_GAUGE,
    CURVE_ETHp_WETH_GAUGE,
    CURVE_WETH_SDT_GAUGE,
    CURVE_PXETH_STETH_GAUGE,
    CURVE_PXETH_FRXETH_GAUGE,
    CURVE_PYUSD_USDC_GAUGE,
    CURVE_CVG_ETH_GAUGE,
    CURVE_cvgSDT_SDT_GAUGE,
    CURVE_cvgCVX_CVX1_GAUGE,
    CURVE_crvUSD_zunUSD_GAUGE,
    CURVE_zunETH_frxETH_GAUGE,
    CURVE_PYUSD_crvUSD_GAUGE,
    CURVE_CVX_ETH_GAUGE,
} from "../erc20/curveGauges";
import {
    SD_FRAX_3CRV,
    SDT_TRI_USDC_WBTC_ETH_GAUGE,
    SDT_crvUSD_USDT_GAUGE,
    SDT_STG_USDC_GAUGE,
    SDT_SDCRV_CRV_GAUGE,
    SDT_FRXETH_ETH_GAUGE,
    SDT_TRI_USDT_WBTC_ETH_1_GAUGE,
    SDT_TRI_crvUSD_TBTC_WSTETH_GAUGE,
    SDT_AGEUR_EUROC_GAUGE,
    SDT_MIM_DAI_USDC_USDT_GAUGE,
    SDT_CVXCRV_CRV_GAUGE,
    SDT_SDFXS_FXS_GAUGE,
    SDT_FRAX_USDC_GAUGE,
    SDT_ALUSD_FRAX_USDC_GAUGE,
    SDT_TRI_USDT_WBTC_ETH_2_GAUGE,
    SDT_RETH_ETH_GAUGE,
    SDT_crvUSD_XAI_GAUGE,
    SDT_COIL_FRAX_USDC_GAUGE,
    SDT_crvUSD_SUSD_GAUGE,
    SDT_crvUSD_DOLA_GAUGE,
    SDT_TRI_crvUSD_ETH_CRV_GAUGE,
    SDT_MKUSD_FRAX_USDC_GAUGE,
    SDT_CNC_ETH_GAUGE,
    SDT_XAI_FRAX_USDC_GAUGE,
    SDT_TRI_crvUSD_FRXETH_SDT_GAUGE,
    SDT_STETH_ETH_GAUGE,
    SDT_DETH_FRXETH_GAUGE,
    SDT_crvUSD_FRAX_GAUGE,
    SDT_ETHp_WETH_GAUGE,
    SDT_WETH_SDT_GAUGE,
    SDT_PXETH_STETH_GAUGE,
    SDT_PXETH_FRXETH_GAUGE,
    SDT_PYUSD_USDC_GAUGE,
    SDT_CVG_ETH_GAUGE,
    SDT_cvgSDT_SDT_GAUGE,
    SDT_cvgCVX_CVX1_GAUGE,
    SDT_crvUSD_zunUSD_GAUGE,
    SDT_zunETH_frxETH_GAUGE,
    SDT_PYUSD_crvUSD_GAUGE,
    SDT_CVX_ETH_GAUGE,
    SDT_crvUSD_USDC_VAULT,
} from "../erc20/stakeDao";
import {
    FRAX3CRV,
    TRI_USDC_WBTC_ETH,
    crvUSD_USDT,
    STG_USDC_LP,
    STG_USDC_POOL,
    SDCRV_CRV,
    crvUSD_USDC,
    FRXETH_ETH_LP,
    FRXETH_ETH_POOL,
    TRI_USDT_WBTC_ETH_1,
    TRI_crvUSD_TBTC_WSTETH,
    AGEUR_EUROC,
    MIM_DAI_USDC_USDT,
    CRV_DUO_cvxCRV_CRV,
    SDFXS_FXS,
    FRAX_USDC_LP,
    FRAX_USDC_POOL,
    ALUSD_FRAX_USDC,
    TRI_USDT_WBTC_ETH_2_LP,
    TRI_USDT_WBTC_ETH_2_POOL,
    RETH_ETH_LP,
    RETH_ETH_POOL,
    crvUSD_XAI,
    COIL_FRAX_USDC_LP,
    COIL_FRAX_USDC_POOL,
    crvUSD_SUSD,
    crvUSD_DOLA,
    TRI_crvUSD_ETH_CRV,
    MKUSD_FRAX_USDC,
    CNC_ETH_LP,
    CNC_ETH_POOL,
    XAI_FRAX_USDC,
    TRI_crvUSD_FRXETH_SDT,
    STETH_ETH_LP,
    STETH_ETH_POOL,
    DETH_FRXETH,
    crvUSD_FRAX,
    ETHp_WETH_LP,
    ETHp_WETH_POOL,
    WETH_SDT_LP,
    WETH_SDT_POOL,
    CRV_DUO_PXETH_FRXETH,
    CRV_DUO_PYUSD_USDC,
    CRV_DUO_CVG_ETH,
    CRV_DUO_cvgSDT_SDT,
    CRV_DUO_cvgCVX_CVX1,
    CRV_DUO_PYUSD_crvUSD,
    CRV_DUO_crvUSD_ZUNUSD,
    CRV_DUO_ZUNETH_FRXETH,
    CRV_LP_pxETH_stETH,
    CRV_DUO_ETH_CVX_TOKEN,
    CRV_DUO_ETH_CVX,
} from "../lps/curve";

export type LpTypeMap = Record<string, { type: string; stake_gauge: string; curve_gauge: string; curve_pool?: string }>;
const TYPE_FACTORY = "factory";
const TYPE_MAIN = "main";
const TYPE_FACTORY_CRYPTO = "factory-crypto";
const TYPE_FACTORY_crvUSD = "factory-crvUSD";
const TYPE_FACTORY_TRICRYPTO = "factory-tricrypto";
const TYPE_FACTORY_STABLE_NG = "factory-stable-ng";
const TYPE_CRYPTO = "crypto";
const TYPE_FACTORY_TWOCRYPTO = "factory-twocrypto";
export const TYPES_CURVE = [
    TYPE_FACTORY,
    TYPE_MAIN,
    TYPE_FACTORY_CRYPTO,
    TYPE_FACTORY_crvUSD,
    TYPE_FACTORY_TRICRYPTO,
    TYPE_CRYPTO,
    TYPE_FACTORY_STABLE_NG,
    TYPE_FACTORY_TWOCRYPTO,
];

export const LPS: LpTypeMap = {
    [FRAX3CRV]: { type: TYPE_MAIN, stake_gauge: SD_FRAX_3CRV, curve_gauge: CURVE_FRAX_3CRV_GAUGE },
    [TRI_USDC_WBTC_ETH]: {
        type: TYPE_FACTORY_TRICRYPTO,
        stake_gauge: SDT_TRI_USDC_WBTC_ETH_GAUGE,
        curve_gauge: CURVE_TRI_USDC_WBTC_ETH_GAUGE,
    },
    [crvUSD_USDT]: { type: TYPE_FACTORY_crvUSD, stake_gauge: SDT_crvUSD_USDT_GAUGE, curve_gauge: CURVE_crvUSD_USDT_GAUGE },
    [STG_USDC_LP]: {
        type: TYPE_FACTORY_CRYPTO,
        stake_gauge: SDT_STG_USDC_GAUGE,
        curve_gauge: CURVE_STG_USDC_GAUGE,
        curve_pool: STG_USDC_POOL,
    },
    [SDCRV_CRV]: { type: TYPE_FACTORY, stake_gauge: SDT_SDCRV_CRV_GAUGE, curve_gauge: CURVE_SDCRV_CRV_GAUGE },
    [crvUSD_USDC]: { type: TYPE_FACTORY_crvUSD, stake_gauge: SDT_crvUSD_USDC_VAULT, curve_gauge: CURVE_crvUSD_USDC_GAUGE },
    [FRXETH_ETH_LP]: {
        type: TYPE_MAIN,
        stake_gauge: SDT_FRXETH_ETH_GAUGE,
        curve_gauge: CURVE_FRXETH_ETH_GAUGE,
        curve_pool: FRXETH_ETH_POOL,
    },
    [TRI_USDT_WBTC_ETH_1]: {
        type: TYPE_FACTORY_TRICRYPTO,
        stake_gauge: SDT_TRI_USDT_WBTC_ETH_1_GAUGE,
        curve_gauge: CURVE_TRI_USDT_WBTC_ETH_1_GAUGE,
    },
    [TRI_crvUSD_TBTC_WSTETH]: {
        type: TYPE_FACTORY_TRICRYPTO,
        stake_gauge: SDT_TRI_crvUSD_TBTC_WSTETH_GAUGE,
        curve_gauge: CURVE_TRI_crvUSD_TBTC_WSTETH_GAUGE,
    },
    [AGEUR_EUROC]: { type: TYPE_FACTORY, stake_gauge: SDT_AGEUR_EUROC_GAUGE, curve_gauge: CURVE_AGEUR_EUROC_GAUGE },
    [MIM_DAI_USDC_USDT]: { type: TYPE_FACTORY, stake_gauge: SDT_MIM_DAI_USDC_USDT_GAUGE, curve_gauge: CURVE_MIM_DAI_USDC_USDT_GAUGE },
    [CRV_DUO_cvxCRV_CRV]: { type: TYPE_FACTORY, stake_gauge: SDT_CVXCRV_CRV_GAUGE, curve_gauge: CURVE_CVXCRV_CRV_GAUGE },
    [SDFXS_FXS]: { type: TYPE_FACTORY, stake_gauge: SDT_SDFXS_FXS_GAUGE, curve_gauge: CURVE_SDFXS_FXS_GAUGE },
    [FRAX_USDC_LP]: {
        type: TYPE_MAIN,
        stake_gauge: SDT_FRAX_USDC_GAUGE,
        curve_gauge: CURVE_FRAX_USDC_GAUGE,
        curve_pool: FRAX_USDC_POOL,
    },
    [ALUSD_FRAX_USDC]: { type: TYPE_FACTORY, stake_gauge: SDT_ALUSD_FRAX_USDC_GAUGE, curve_gauge: CURVE_ALUSD_FRAX_USDC_GAUGE },
    [TRI_USDT_WBTC_ETH_2_LP]: {
        type: TYPE_CRYPTO,
        stake_gauge: SDT_TRI_USDT_WBTC_ETH_2_GAUGE,
        curve_gauge: CURVE_TRI_USDT_WBTC_ETH_2_GAUGE,
        curve_pool: TRI_USDT_WBTC_ETH_2_POOL,
    },
    [RETH_ETH_LP]: {
        type: TYPE_MAIN,
        stake_gauge: SDT_RETH_ETH_GAUGE,
        curve_gauge: CURVE_RETH_ETH_GAUGE,
        curve_pool: RETH_ETH_POOL,
    },
    [crvUSD_XAI]: { type: TYPE_FACTORY_crvUSD, stake_gauge: SDT_crvUSD_XAI_GAUGE, curve_gauge: CURVE_crvUSD_XAI_GAUGE },
    [COIL_FRAX_USDC_LP]: {
        type: TYPE_FACTORY_CRYPTO,
        stake_gauge: SDT_COIL_FRAX_USDC_GAUGE,
        curve_gauge: CURVE_COIL_FRAX_USDC_GAUGE,
        curve_pool: COIL_FRAX_USDC_POOL,
    },
    [crvUSD_SUSD]: { type: TYPE_FACTORY_crvUSD, stake_gauge: SDT_crvUSD_SUSD_GAUGE, curve_gauge: CURVE_crvUSD_SUSD_GAUGE },
    [crvUSD_DOLA]: { type: TYPE_FACTORY_crvUSD, stake_gauge: SDT_crvUSD_DOLA_GAUGE, curve_gauge: CURVE_crvUSD_DOLA_GAUGE },
    [TRI_crvUSD_ETH_CRV]: {
        type: TYPE_FACTORY_TRICRYPTO,
        stake_gauge: SDT_TRI_crvUSD_ETH_CRV_GAUGE,
        curve_gauge: CURVE_TRI_crvUSD_ETH_CRV_GAUGE,
    },
    [MKUSD_FRAX_USDC]: { type: TYPE_FACTORY, stake_gauge: SDT_MKUSD_FRAX_USDC_GAUGE, curve_gauge: CURVE_MKUSD_FRAX_USDC_GAUGE },
    [CNC_ETH_LP]: { type: TYPE_FACTORY_CRYPTO, stake_gauge: SDT_CNC_ETH_GAUGE, curve_gauge: CURVE_CNC_ETH_GAUGE, curve_pool: CNC_ETH_POOL },
    [XAI_FRAX_USDC]: { type: TYPE_FACTORY, stake_gauge: SDT_XAI_FRAX_USDC_GAUGE, curve_gauge: CURVE_XAI_FRAX_USDC_GAUGE },
    [TRI_crvUSD_FRXETH_SDT]: {
        type: TYPE_FACTORY_TRICRYPTO,
        stake_gauge: SDT_TRI_crvUSD_FRXETH_SDT_GAUGE,
        curve_gauge: CURVE_TRI_crvUSD_FRXETH_SDT_GAUGE,
    },
    [STETH_ETH_LP]: {
        type: TYPE_MAIN,
        stake_gauge: SDT_STETH_ETH_GAUGE,
        curve_gauge: CURVE_STETH_ETH_GAUGE,
        curve_pool: STETH_ETH_POOL,
    },
    [DETH_FRXETH]: { type: TYPE_FACTORY, stake_gauge: SDT_DETH_FRXETH_GAUGE, curve_gauge: CURVE_DETH_FRXETH_GAUGE },
    [crvUSD_FRAX]: { type: TYPE_FACTORY_crvUSD, stake_gauge: SDT_crvUSD_FRAX_GAUGE, curve_gauge: CURVE_crvUSD_FRAX_GAUGE },
    [ETHp_WETH_LP]: {
        type: TYPE_FACTORY_CRYPTO,
        stake_gauge: SDT_ETHp_WETH_GAUGE,
        curve_gauge: CURVE_ETHp_WETH_GAUGE,
        curve_pool: ETHp_WETH_POOL,
    },
    [WETH_SDT_LP]: {
        type: TYPE_FACTORY_CRYPTO,
        stake_gauge: SDT_WETH_SDT_GAUGE,
        curve_gauge: CURVE_WETH_SDT_GAUGE,
        curve_pool: WETH_SDT_POOL,
    },

    [CRV_LP_pxETH_stETH]: {
        type: TYPE_FACTORY_STABLE_NG,
        stake_gauge: SDT_PXETH_STETH_GAUGE,
        curve_gauge: CURVE_PXETH_STETH_GAUGE,
    },

    [CRV_DUO_PXETH_FRXETH]: {
        type: TYPE_FACTORY_STABLE_NG,
        stake_gauge: SDT_PXETH_FRXETH_GAUGE,
        curve_gauge: CURVE_PXETH_FRXETH_GAUGE,
    },
    [CRV_DUO_PYUSD_USDC]: {
        type: TYPE_FACTORY_STABLE_NG,
        stake_gauge: SDT_PYUSD_USDC_GAUGE,
        curve_gauge: CURVE_PYUSD_USDC_GAUGE,
    },

    [CRV_DUO_CVG_ETH]: {
        type: TYPE_FACTORY_TWOCRYPTO,
        stake_gauge: SDT_CVG_ETH_GAUGE,
        curve_gauge: CURVE_CVG_ETH_GAUGE,
    },
    [CRV_DUO_cvgSDT_SDT]: {
        type: TYPE_FACTORY_STABLE_NG,
        stake_gauge: SDT_cvgSDT_SDT_GAUGE,
        curve_gauge: CURVE_cvgSDT_SDT_GAUGE,
    },
    [CRV_DUO_cvgCVX_CVX1]: {
        type: TYPE_FACTORY_STABLE_NG,
        stake_gauge: SDT_cvgCVX_CVX1_GAUGE,
        curve_gauge: CURVE_cvgCVX_CVX1_GAUGE,
    },
    [CRV_DUO_crvUSD_ZUNUSD]: {
        type: TYPE_FACTORY_STABLE_NG,
        stake_gauge: SDT_crvUSD_zunUSD_GAUGE,
        curve_gauge: CURVE_crvUSD_zunUSD_GAUGE,
    },
    [CRV_DUO_ZUNETH_FRXETH]: {
        type: TYPE_FACTORY_STABLE_NG,
        stake_gauge: SDT_zunETH_frxETH_GAUGE,
        curve_gauge: CURVE_zunETH_frxETH_GAUGE,
    },
    [CRV_DUO_PYUSD_crvUSD]: {
        type: TYPE_FACTORY_STABLE_NG,
        stake_gauge: SDT_PYUSD_crvUSD_GAUGE,
        curve_gauge: CURVE_PYUSD_crvUSD_GAUGE,
    },
    [CRV_DUO_ETH_CVX_TOKEN]: {
        type: TYPE_MAIN,
        stake_gauge: SDT_CVX_ETH_GAUGE,
        curve_gauge: CURVE_CVX_ETH_GAUGE,
        curve_pool: CRV_DUO_ETH_CVX,
    },

};
